version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 20 1
    volumes:
      - redis-data:/data
    restart: always
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    restart: always
