app = "go-gemma"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
dockerfile = "Dockerfile"
ignorefile = ".dockerignore"

[[mounts]]
source = "data"
destination = "/app/data"
auto_extend_size_threshold = 0

[http_service]
internal_port = 8081
force_https = true
auto_stop_machines = true
auto_start_machines = true

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[vm]]
cpu_kind = "shared"
cpus = 4
memory_mb = 6144
